 ## 1 - Preparação dos Dados
Fonte: Microdados de Matrículas da Plataforma Nilo Peçanha (2017-2024)

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

#### 1.1 Transformação dos arquivos .csv em Data Frames, selecionando as colunas a serem utilizadas:

In [2]:
selecao = [
    "Ano", "Carga Horaria", "Carga Horaria Mínima", "Categoria da Situação", 
    "Cor / Raça", "Código da Matricula", "Código do Ciclo Matricula", 
    "Data de Fim Previsto do Ciclo", 
    "Data de Inicio do Ciclo", "Data de Ocorrencia da Matricula", 
    "Eixo Tecnológico", "Faixa Etária", "Fator Esforço Curso", 
    "Idade", "Instituição", 
    "Modalidade de Ensino", "Município", "Mês De Ocorrência da Situação", 
    "Nome de Curso", "Renda Familiar", "Sexo", 
    "Situação de Matrícula", "Subeixo Tecnológico", "Tipo de Curso", 
    "Tipo de Oferta", "Total de Inscritos", "Turno", "UF", "Unidade de Ensino"
]


df_2017 = pd.read_csv("../dados_brutos/microdados_matriculas_2017.csv", sep=";", usecols=selecao)
df_2018 = pd.read_csv("../dados_brutos/microdados_matriculas_2018.csv", sep=";", usecols=selecao)
df_2019 = pd.read_csv("../dados_brutos/microdados_matriculas_2019.csv", sep=";", usecols=selecao)
df_2020 = pd.read_csv("../dados_brutos/microdados_matriculas_2020.csv", sep=";", usecols=selecao)
df_2021 = pd.read_csv("../dados_brutos/microdados_matriculas_2021.csv", sep=";", usecols=selecao)
df_2022 = pd.read_csv("../dados_brutos/microdados_matriculas_2022.csv", sep=";", usecols=selecao)
df_2023 = pd.read_csv("../dados_brutos/microdados_matriculas_2023.csv", sep=";", usecols=selecao)
df_2024 = pd.read_csv("../dados_brutos/microdados_matriculas_2024.csv", sep=";", usecols=selecao)


print("Dimensão original 2017:", df_2017.shape)
print("Dimensão original 2018:", df_2018.shape)
print("Dimensão original 2019:", df_2019.shape)
print("Dimensão original 2020:", df_2020.shape)
print("Dimensão original 2021:", df_2021.shape)
print("Dimensão original 2022:", df_2022.shape)
print("Dimensão original 2023:", df_2023.shape)
print("Dimensão original 2024:", df_2024.shape)

Dimensão original 2017: (1031798, 29)
Dimensão original 2018: (964593, 29)
Dimensão original 2019: (1023303, 29)
Dimensão original 2020: (1507476, 29)
Dimensão original 2021: (1523346, 29)
Dimensão original 2022: (1513075, 29)
Dimensão original 2023: (1681363, 29)
Dimensão original 2024: (1982778, 29)

#### 1.2 Concatenação dos Data Frames gerados e exibição dos primeiros e últimos registros:

In [3]:
df_2017_2024 = pd.concat([df_2017, df_2018, df_2019, df_2020, df_2021, df_2022, df_2023, df_2024])

df_2017_2024.head()

,Ano,Carga Horaria,Carga Horaria Mínima,Categoria da Situação,Cor / Raça,Código da Matricula,Código do Ciclo Matricula,Data de Fim Previsto do Ciclo,Data de Inicio do Ciclo,Data de Ocorrencia da Matricula,Eixo Tecnológico,Faixa Etária,Fator Esforço Curso,Idade,Instituição,Modalidade de Ensino,Município,Mês De Ocorrência da Situação,Nome de Curso,Renda Familiar,Sexo,Situação de Matrícula,Subeixo Tecnológico,Tipo de Curso,Tipo de Oferta,Total de Inscritos,Turno,UF,Unidade de Ensino
0,2017,3140,1200.0,Em curso,Parda,72203790,2152673,31/12/2019,02/03/2017,01/03/2017,Produção Alimentícia,15 a 19 anos,"1,15",17.0,IFRR,Educação Presencial,Norte,01/03/2017,Técnico em Agroindústria,"0,5<RFP<=1",M,Em curso,Agroindustria,Técnico,Integrado,52.0,Integral,RR,Campus Novo Paraíso
1,2017,3140,1200.0,Em curso,Parda,72203780,2152673,31/12/2019,02/03/2017,01/03/2017,Produção Alimentícia,15 a 19 anos,"1,15",17.0,IFRR,Educação Presencial,Norte,01/03/2017,Técnico em Agroindústria,"1<RFP<=1,5",M,Em curso,Agroindustria,Técnico,Integrado,52.0,Integral,RR,Campus Novo Paraíso
2,2017,3140,1200.0,Evadidos,Preta,72203776,2152673,31/12/2019,02/03/2017,01/03/2017,Produção Alimentícia,15 a 19 anos,"1,15",15.0,IFRR,Educação Presencial,Norte,01/07/2017,Técnico em Agroindústria,"0,5<RFP<=1",M,Transf. externa,Agroindustria,Técnico,Integrado,52.0,Integral,RR,Campus Novo Paraíso
3,2017,3140,1200.0,Em curso,Parda,72203774,2152673,31/12/2019,02/03/2017,01/03/2017,Produção Alimentícia,15 a 19 anos,"1,15",16.0,IFRR,Educação Presencial,Norte,01/03/2017,Técnico em Agroindústria,"RFP>3,5",F,Em curso,Agroindustria,Técnico,Integrado,52.0,Integral,RR,Campus Novo Paraíso
4,2017,3140,1200.0,Em curso,Parda,72203772,2152673,31/12/2019,02/03/2017,01/03/2017,Produção Alimentícia,15 a 19 anos,"1,15",15.0,IFRR,Educação Presencial,Norte,01/03/2017,Técnico em Agroindústria,"0,5<RFP<=1",M,Em curso,Agroindustria,Técnico,Integrado,52.0,Integral,RR,Campus Novo Paraíso

In [4]:
df_2017_2024.tail()

,Ano,Carga Horaria,Carga Horaria Mínima,Categoria da Situação,Cor / Raça,Código da Matricula,Código do Ciclo Matricula,Data de Fim Previsto do Ciclo,Data de Inicio do Ciclo,Data de Ocorrencia da Matricula,Eixo Tecnológico,Faixa Etária,Fator Esforço Curso,Idade,Instituição,Modalidade de Ensino,Município,Mês De Ocorrência da Situação,Nome de Curso,Renda Familiar,Sexo,Situação de Matrícula,Subeixo Tecnológico,Tipo de Curso,Tipo de Oferta,Total de Inscritos,Turno,UF,Unidade de Ensino
1982773,2024,3240,1200.0,Em curso,Parda,109548323,2965961,20/12/2025,27/02/2023,01/02/2023,Controle e Processos Industriais,15 a 19 anos,"1,12",17.0,IF SUDESTE MG,Educação Presencial,Muriaé,25/02/2023,Técnico em Eletrotécnica,"0,5<RFP<=1",F,Em curso,Elétrica,Técnico,Integrado,96.0,Integral,MG,Campus Muriaé
1982774,2024,60,160.0,Concluintes,Parda,122954788,3139052,20/12/2024,01/07/2024,01/11/2024,Gestão e Negócios,35 a 39 anos,"1,1",37.0,IFMS,Educação a Distância,Campo Grande,25/11/2024,Qualificação Profissional - Gestão e Negócios,"0,5<RFP<=1",M,Concluída,Gestão e Negócios,Qualificação Profissional (FIC),Concomitante,1346.0,NaN,MS,Campus Campo Grande
1982775,2024,3300,800.0,Concluintes,Parda,99499494,2774414,01/03/2024,03/05/2021,01/05/2021,Gestão e Negócios,15 a 19 anos,"1,008",19.0,IFPI,Educação Presencial,Oeiras,25/01/2024,Técnico em Administração,"0<RFP<=0,5",F,Concluída,Gestão e Negócios,Técnico,Integrado,154.0,Matutino,PI,Campus Oeiras
1982776,2024,1050,800.0,Concluintes,Parda,106556867,2906230,31/01/2024,09/08/2022,01/08/2022,Gestão e Negócios,40 a 44 anos,"1,005",42.0,IFPE,Educação Presencial,Cabo de Santo Agostinho,25/02/2024,Técnico em Logística,"0,5<RFP<=1",F,Concluída,Gestão e Negócios,Técnico,Subsequente,347.0,Vespertino,PE,Campus Cabo de Santo Agostinho
1982777,2024,1440,1000.0,Evadidos,Branca,111688442,2995963,31/07/2025,20/03/2023,01/03/2023,Informação e Comunicação,20 a 24 anos,"1,053",23.0,IFCE,Educação Presencial,Canindé,25/12/2024,Técnico em Informática,Não declarada,F,Abandono,Informática,Técnico,Subsequente,35.0,Noturno,CE,Campus Canindé

#### 1.3 Aplicação de Filtro de Unidade de Ensino = Campus Porto Alegre Restinga:

In [5]:
df_restinga = df_2017_2024.loc[df_2017_2024["Unidade de Ensino"] == "Campus Porto Alegre Restinga"]
print("Após filtro Campus Restinga:", df_restinga.shape)

Após filtro Campus Restinga: (16850, 29)

#### 1.4 Exclusão de colunas desnecessárias:

In [6]:
df_restinga = df_restinga.drop(columns=["Instituição", "Município", "UF", "Unidade de Ensino"])
print("Após exclusão de colunas desnecessárias:", df_restinga.shape)

Após exclusão de colunas desnecessárias: (16850, 25)

#### 1.5 Verificação dos nomes dos cursos do Campus Restinga:

In [7]:
df_restinga.groupby("Nome de Curso").size()

Nome de Curso
Agente Cultural                                                       36
Agente de Desenvolvimento Cooperativista                              25
Análise e Desenvolvimento de Sistemas                               2209
Confeccionador de Bolsas em Tecido                                    25
Eletrônica Industrial                                                854
Gestor de Microempresa                                                29
Gestão Desportiva e de Lazer                                          84
Gestão desportiva e de Lazer                                         713
Letras                                                               177
Letras - Língua Estrangeira                                          620
Língua Brasileira de Sinais (Libras) ­ Básico                         25
Manufatura Avançada (industria 4.0)                                   15
Monitor de Atividades de Lazer                                        23
Operador de Computador                                                83
Processos Gerenciais                                                 764
Qualificação Profissional - Controle e Processos Industriais          36
Qualificação Profissional - Desenvolvimento Educacional e Social    5369
Técnico em Administração                                             168
Técnico em Agroecologia                                              747
Técnico em Comércio                                                  754
Técnico em Eletrônica                                               1076
Técnico em Guia de Turismo                                           554
Técnico em Informática                                              1126
Técnico em Informática Para Internet                                   3
Técnico em Informática para Internet                                 247
Técnico em Lazer                                                     769
Técnico em Recursos Humanos                                          195
Técnico em Redes de Computadores                                     124
dtype: int64

#### 1.6 Seleção dos cursos Técnicos e Superiores do Campus Restinga:

In [8]:
df_restinga["Tipo de Curso"].unique()

array(['Tecnologia', 'Técnico', 'Licenciatura',
       'Qualificação Profissional (FIC)', 'Especialização (Lato Sensu)'],
      dtype=object)

In [9]:
df_restinga = df_restinga[
    df_restinga["Tipo de Curso"].isin(["Licenciatura", "Técnico", "Tecnologia"])
]

In [10]:
df_contagem = df_restinga.groupby("Nome de Curso").size()
df_contagem

Nome de Curso
Análise e Desenvolvimento de Sistemas    2209
Eletrônica Industrial                     854
Gestão Desportiva e de Lazer               84
Gestão desportiva e de Lazer              713
Letras                                    177
Letras - Língua Estrangeira               620
Processos Gerenciais                      764
Técnico em Administração                  168
Técnico em Agroecologia                   747
Técnico em Comércio                       754
Técnico em Eletrônica                    1076
Técnico em Guia de Turismo                554
Técnico em Informática                   1126
Técnico em Informática Para Internet        3
Técnico em Informática para Internet      247
Técnico em Lazer                          769
Técnico em Recursos Humanos               195
Técnico em Redes de Computadores          124
dtype: int64

In [11]:
df_restinga["Código da Matricula"].count()

np.int64(11184)

#### 1.7 Limpeza dos cursos extintos e padronização dos nomes:

In [16]:
cursos_excluir = [
    "Técnico em Administração",
    "Técnico em Informática Para Internet",
    "Técnico em Informática para Internet",
    "Técnico em Recursos Humanos",
    "Técnico em Redes de Computadores"
]

df_restinga = df_restinga[
    ~df_restinga["Nome de Curso"].isin(cursos_excluir)
]

df_restinga.loc[:, "Nome de Curso"] = df_restinga["Nome de Curso"].replace({
    "Gestão desportiva e de Lazer": "Gestão Desportiva e de Lazer",
    "Letras": "Letras - Português e Espanhol",
    "Letras - Língua Estrangeira": "Letras - Português e Espanhol"
})

df_restinga["Nome de Curso"].unique()

array(['Análise e Desenvolvimento de Sistemas', 'Técnico em Eletrônica',
       'Gestão Desportiva e de Lazer', 'Eletrônica Industrial',
       'Técnico em Informática', 'Técnico em Guia de Turismo',
       'Técnico em Comércio', 'Técnico em Lazer',
       'Letras - Português e Espanhol', 'Processos Gerenciais',
       'Técnico em Agroecologia'], dtype=object)

#### 1.9 Verificando os valores ausentes:

In [17]:
df_restinga.isnull().sum()   # df_restinga.isna().sum()  #esse comando é equivalente

Ano                                   0
Carga Horaria                         0
Carga Horaria Mínima                  0
Categoria da Situação                 0
Cor / Raça                            0
Código da Matricula                   0
Código do Ciclo Matricula             0
Data de Fim Previsto do Ciclo         0
Data de Inicio do Ciclo               0
Data de Ocorrencia da Matricula       0
Eixo Tecnológico                      0
Faixa Etária                          0
Fator Esforço Curso                   0
Idade                                 0
Modalidade de Ensino                  0
Mês De Ocorrência da Situação         2
Nome de Curso                         0
Renda Familiar                        0
Sexo                                  0
Situação de Matrícula                 0
Subeixo Tecnológico                   0
Tipo de Curso                         0
Tipo de Oferta                        0
Total de Inscritos                 1978
Turno                                 0
dtype: int64

#### 1.10 Tratamento dos valores ausentes:

In [18]:
#retirar coluna total inscritos, porque não será necessária ao cálculo dos indicadores
df_restinga = df_restinga.drop(columns=["Total de Inscritos"])
print("Após exclusão de total de inscritos:", df_restinga.shape)

Após exclusão de total de inscritos: (10447, 24)

In [19]:
#retirar as 2 linhas com valores nulos do mês de ocorrência

df_restinga.dropna(subset=["Mês De Ocorrência da Situação"], inplace=True) #inplace=True para salvar a retirada dos nulos --- verificar se faremos assim

print("Após exclusão de linhas desnecessárias:", df_restinga.shape)

Após exclusão de linhas desnecessárias: (10445, 24)

In [20]:
df_restinga.isnull().sum()

Ano                                0
Carga Horaria                      0
Carga Horaria Mínima               0
Categoria da Situação              0
Cor / Raça                         0
Código da Matricula                0
Código do Ciclo Matricula          0
Data de Fim Previsto do Ciclo      0
Data de Inicio do Ciclo            0
Data de Ocorrencia da Matricula    0
Eixo Tecnológico                   0
Faixa Etária                       0
Fator Esforço Curso                0
Idade                              0
Modalidade de Ensino               0
Mês De Ocorrência da Situação      0
Nome de Curso                      0
Renda Familiar                     0
Sexo                               0
Situação de Matrícula              0
Subeixo Tecnológico                0
Tipo de Curso                      0
Tipo de Oferta                     0
Turno                              0
dtype: int64

#### 1.11 Verificando os tipos de dados:

In [21]:
df_restinga.dtypes

Ano                                  int64
Carga Horaria                        int64
Carga Horaria Mínima               float64
Categoria da Situação               object
Cor / Raça                          object
Código da Matricula                  int64
Código do Ciclo Matricula            int64
Data de Fim Previsto do Ciclo       object
Data de Inicio do Ciclo             object
Data de Ocorrencia da Matricula     object
Eixo Tecnológico                    object
Faixa Etária                        object
Fator Esforço Curso                 object
Idade                              float64
Modalidade de Ensino                object
Mês De Ocorrência da Situação       object
Nome de Curso                       object
Renda Familiar                      object
Sexo                                object
Situação de Matrícula               object
Subeixo Tecnológico                 object
Tipo de Curso                       object
Tipo de Oferta                      object
Turno                               object
dtype: object

#### 1.12 Convertendo os tipos de dados:

In [22]:

df_restinga["Data de Fim Previsto do Ciclo"] = pd.to_datetime(
    df_restinga["Data de Fim Previsto do Ciclo"],
    dayfirst=True,
    errors='coerce'
)

df_restinga["Data de Inicio do Ciclo"] = pd.to_datetime(
    df_restinga["Data de Inicio do Ciclo"],
    dayfirst=True,
    errors='coerce'
)
df_restinga["Data de Ocorrencia da Matricula"] = pd.to_datetime(
    df_restinga["Data de Ocorrencia da Matricula"],
    dayfirst=True,
    errors='coerce'
)

df_restinga["Mês De Ocorrência da Situação"] = pd.to_datetime(
    df_restinga["Mês De Ocorrência da Situação"],
    dayfirst=True,
    errors='coerce'
)

df_restinga.dtypes

Ano                                         int64
Carga Horaria                               int64
Carga Horaria Mínima                      float64
Categoria da Situação                      object
Cor / Raça                                 object
Código da Matricula                         int64
Código do Ciclo Matricula                   int64
Data de Fim Previsto do Ciclo      datetime64[ns]
Data de Inicio do Ciclo            datetime64[ns]
Data de Ocorrencia da Matricula    datetime64[ns]
Eixo Tecnológico                           object
Faixa Etária                               object
Fator Esforço Curso                        object
Idade                                     float64
Modalidade de Ensino                       object
Mês De Ocorrência da Situação      datetime64[ns]
Nome de Curso                              object
Renda Familiar                             object
Sexo                                       object
Situação de Matrícula                      object
Subeixo Tecnológico                        object
Tipo de Curso                              object
Tipo de Oferta                             object
Turno                                      object
dtype: object

#### Ajustes das situações de matrícula:

In [23]:
df_restinga["Situação de Matrícula"].unique()

array(['Em curso', 'Transf. externa', 'Desligada', 'Abandono',
       'Concluída', 'Integralizada', 'Transf. interna'], dtype=object)

In [24]:
# ajuste matrículas Em curso para Retido ou Em fluxo:
periodo_fim_previsto = df_restinga["Data de Fim Previsto do Ciclo"].dt.to_period("M")
periodo_referencia = pd.PeriodIndex.from_fields(
    year=df_restinga["Ano"],
    month=12,
    freq="M"
)

df_restinga.loc[df_restinga["Situação de Matrícula"] == "Em curso", "Situação de Matrícula"] = np.where(
    periodo_fim_previsto[df_restinga["Situação de Matrícula"] == "Em curso"] < periodo_referencia[df_restinga["Situação de Matrícula"] == "Em curso"],
    "Retido",
    "Em fluxo"
)

# ajuste matrículas Concluída para Concluída no prazo ou Concluída com atraso:
periodo_conclusao = df_restinga["Mês De Ocorrência da Situação"].dt.to_period("M")

# Diferença em meses
diferenca_meses = (
    periodo_conclusao.astype(int) - periodo_fim_previsto.astype(int)
)

# Classificação
df_restinga.loc[df_restinga["Situação de Matrícula"] == "Concluída", "Situação de Matrícula"] = np.where(
    diferenca_meses[df_restinga["Situação de Matrícula"] == "Concluída"] <= 5,
    "Concluída no prazo",
    "Concluída com atraso"
)

df_restinga["Situação de Matrícula"].value_counts()

Situação de Matrícula
Em fluxo                6684
Retido                  2316
Abandono                 449
Concluída no prazo       379
Concluída com atraso     259
Desligada                244
Transf. externa          103
Transf. interna            6
Integralizada              5
Name: count, dtype: int64

#### 1.13 Inspeção detalhada:

In [25]:
df_restinga.info(memory_usage='deep') #para verificar a utilização de memória real

<class 'pandas.core.frame.DataFrame'>
Index: 10445 entries, 20729 to 1981342
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Ano                              10445 non-null  int64
 1   Carga Horaria                    10445 non-null  int64
 2   Carga Horaria Mínima             10445 non-null  float64
 3   Categoria da Situação            10445 non-null  object
 4   Cor / Raça                       10445 non-null  object
 5   Código da Matricula              10445 non-null  int64
 6   Código do Ciclo Matricula        10445 non-null  int64
 7   Data de Fim Previsto do Ciclo    10445 non-null  datetime64[ns]
 8   Data de Inicio do Ciclo          10445 non-null  datetime64[ns]
 9   Data de Ocorrencia da Matricula  10445 non-null  datetime64[ns]
 10  Eixo Tecnológico                 10445 non-null  object
 11  Faixa Etária                     10445 non-null  object
 12  Fator Esforço Curso              10445 non-null  object
 13  Idade                            10445 non-null  float64
 14  Modalidade de Ensino             10445 non-null  object
 15  Mês De Ocorrência da Situação    10445 non-null  datetime64[ns]
 16  Nome de Curso                    10445 non-null  object
 17  Renda Familiar                   10445 non-null  object
 18  Sexo                             10445 non-null  object
 19  Situação de Matrícula            10445 non-null  object
 20  Subeixo Tecnológico              10445 non-null  object
 21  Tipo de Curso                    10445 non-null  object
 22  Tipo de Oferta                   10445 non-null  object
 23  Turno                            10445 non-null  object
dtypes: datetime64[ns](4), float64(2), int64(4), object(14)
memory usage: 10.3 MB

#### 1.14 Exportando o DataFrame para .parquet

In [26]:
df_restinga.to_parquet("teste_restinga_dados_preparados.parquet", index=False)