 ## 1 - Preparação dos Dados
Fonte: Microdados de Matrículas da Plataforma Nilo Peçanha (2017-2025)

In [67]:
import pandas as pd

pd.set_option("display.max_columns", None)

#### 1.1 Transformação dos arquivos .csv em Data Frames, selecionando as colunas a serem utilizadas:

In [68]:
selecao = [
    "Ano", "Categoria da Situação", "Cor / Raça", "Código da Matricula", "Código do Ciclo Matricula", 
    "Data de Fim Previsto do Ciclo", "Data de Inicio do Ciclo", "Data de Ocorrencia da Matricula", 
    "Eixo Tecnológico", "Faixa Etária", "Instituição", "Município", "Mês De Ocorrência da Situação", 
    "Nome de Curso", "Renda Familiar", "Sexo", "Situação de Matrícula", "Subeixo Tecnológico", 
    "Tipo de Curso", "Tipo de Oferta", "Total de Inscritos", "Turno", "UF", "Unidade de Ensino"
]


df_2017 = pd.read_csv("../dados_brutos/microdados_matriculas_2017.csv", sep=";", usecols=selecao)
df_2018 = pd.read_csv("../dados_brutos/microdados_matriculas_2018.csv", sep=";", usecols=selecao)
df_2019 = pd.read_csv("../dados_brutos/microdados_matriculas_2019.csv", sep=";", usecols=selecao)
df_2020 = pd.read_csv("../dados_brutos/microdados_matriculas_2020.csv", sep=";", usecols=selecao)
df_2021 = pd.read_csv("../dados_brutos/microdados_matriculas_2021.csv", sep=";", usecols=selecao)
df_2022 = pd.read_csv("../dados_brutos/microdados_matriculas_2022.csv", sep=";", usecols=selecao)
df_2023 = pd.read_csv("../dados_brutos/microdados_matriculas_2023.csv", sep=";", usecols=selecao)
df_2024 = pd.read_csv("../dados_brutos/microdados_matriculas_2024.csv", sep=";", usecols=selecao)
df_2025 = pd.read_csv("../dados_brutos/microdados_matriculas_2025.csv", sep=";", usecols=selecao)


print("Dimensão original 2017:", df_2017.shape)
print("Dimensão original 2018:", df_2018.shape)
print("Dimensão original 2019:", df_2019.shape)
print("Dimensão original 2020:", df_2020.shape)
print("Dimensão original 2021:", df_2021.shape)
print("Dimensão original 2022:", df_2022.shape)
print("Dimensão original 2023:", df_2023.shape)
print("Dimensão original 2024:", df_2024.shape)
print("Dimensão original 2025:", df_2025.shape)

Dimensão original 2017: (1031798, 24)
Dimensão original 2018: (964593, 24)
Dimensão original 2019: (1023303, 24)
Dimensão original 2020: (1507476, 24)
Dimensão original 2021: (1523346, 24)
Dimensão original 2022: (1513075, 24)
Dimensão original 2023: (1681363, 24)
Dimensão original 2024: (1982778, 24)
Dimensão original 2025: (2386962, 24)

#### 1.2 Concatenação dos Data Frames gerados e exibição dos primeiros e últimos registros:

In [69]:
df_2017_2025 = pd.concat([df_2017, df_2018, df_2019, df_2020, df_2021, df_2022, df_2023, df_2024, df_2025])

df_2017_2025.head()

,Ano,Categoria da Situação,Cor / Raça,Código da Matricula,Código do Ciclo Matricula,Data de Fim Previsto do Ciclo,Data de Inicio do Ciclo,Data de Ocorrencia da Matricula,Eixo Tecnológico,Faixa Etária,Instituição,Município,Mês De Ocorrência da Situação,Nome de Curso,Renda Familiar,Sexo,Situação de Matrícula,Subeixo Tecnológico,Tipo de Curso,Tipo de Oferta,Total de Inscritos,Turno,UF,Unidade de Ensino
0,2017,Em curso,Parda,72203790,2152673,31/12/2019,02/03/2017,01/03/2017,Produção Alimentícia,15 a 19 anos,IFRR,Norte,01/03/2017,Técnico em Agroindústria,"0,5<RFP<=1",M,Em curso,Agroindustria,Técnico,Integrado,52.0,Integral,RR,Campus Novo Paraíso
1,2017,Em curso,Parda,72203780,2152673,31/12/2019,02/03/2017,01/03/2017,Produção Alimentícia,15 a 19 anos,IFRR,Norte,01/03/2017,Técnico em Agroindústria,"1<RFP<=1,5",M,Em curso,Agroindustria,Técnico,Integrado,52.0,Integral,RR,Campus Novo Paraíso
2,2017,Evadidos,Preta,72203776,2152673,31/12/2019,02/03/2017,01/03/2017,Produção Alimentícia,15 a 19 anos,IFRR,Norte,01/07/2017,Técnico em Agroindústria,"0,5<RFP<=1",M,Transf. externa,Agroindustria,Técnico,Integrado,52.0,Integral,RR,Campus Novo Paraíso
3,2017,Em curso,Parda,72203774,2152673,31/12/2019,02/03/2017,01/03/2017,Produção Alimentícia,15 a 19 anos,IFRR,Norte,01/03/2017,Técnico em Agroindústria,"RFP>3,5",F,Em curso,Agroindustria,Técnico,Integrado,52.0,Integral,RR,Campus Novo Paraíso
4,2017,Em curso,Parda,72203772,2152673,31/12/2019,02/03/2017,01/03/2017,Produção Alimentícia,15 a 19 anos,IFRR,Norte,01/03/2017,Técnico em Agroindústria,"0,5<RFP<=1",M,Em curso,Agroindustria,Técnico,Integrado,52.0,Integral,RR,Campus Novo Paraíso

In [70]:
df_2017_2025.tail()

,Ano,Categoria da Situação,Cor / Raça,Código da Matricula,Código do Ciclo Matricula,Data de Fim Previsto do Ciclo,Data de Inicio do Ciclo,Data de Ocorrencia da Matricula,Eixo Tecnológico,Faixa Etária,Instituição,Município,Mês De Ocorrência da Situação,Nome de Curso,Renda Familiar,Sexo,Situação de Matrícula,Subeixo Tecnológico,Tipo de Curso,Tipo de Oferta,Total de Inscritos,Turno,UF,Unidade de Ensino
2386957,2025,Em curso,Parda,109778605,2965950,30/09/2026,16/02/2023,01/02/2023,Gestão e Negócios,20 a 24 anos,IFPE,Igarassu,25/02/2023,Gestão da Qualidade,"0,5<RFP<=1",F,Em curso,Gestão e Negócios,Tecnologia,Não se aplica,51.0,Matutino,PE,Campus Igarassu
2386958,2025,Evadidos,Não declarada,109440039,2963966,07/02/2024,07/03/2023,01/03/2023,Desenvolvimento Educacional e Social,30 a 34 anos,IF GOIANO,Iporá,25/11/2025,Língua Brasileira de Sinais (Libras) ­ Básico,Não declarada,F,Abandono,Desenvolvimento Educacional,Qualificação Profissional (FIC),Subsequente,60.0,Vespertino,GO,Campus Iporá
2386959,2025,Em curso,Não declarada,122044988,3174385,03/08/2026,01/11/2024,01/11/2024,Desenvolvimento Educacional e Social,30 a 34 anos,IF GOIANO,Iporá,25/11/2024,Pós-graduação Lato Sensu em Docência Na Educaç...,Não declarada,F,Em curso,Desenvolvimento Educacional e Social,Especialização (Lato Sensu),Não se aplica,30.0,NaN,GO,Campus Iporá
2386960,2025,Concluintes,Branca,129144127,3274654,30/07/2025,01/07/2025,01/07/2025,Gestão e Negócios,20 a 24 anos,IFRS,Bento Gonçalves,25/08/2025,Qualificação Profissional - Gestão e Negócios,"0,5<RFP<=1",F,Concluída,Gestão e Negócios,Qualificação Profissional (FIC),Não se aplica,498.0,NaN,RS,Campus Bento Gonçalves
2386961,2025,Concluintes,Branca,129107291,3274347,30/07/2025,01/07/2025,01/07/2025,Gestão e Negócios,20 a 24 anos,IFRS,Bento Gonçalves,25/08/2025,Qualificação Profissional - Gestão e Negócios,"0,5<RFP<=1",F,Concluída,Gestão e Negócios,Qualificação Profissional (FIC),Não se aplica,111.0,NaN,RS,Campus Bento Gonçalves

#### 1.3 Aplicação de Filtro de Unidade de Ensino = Campus Porto Alegre Restinga:

In [71]:
df_restinga = df_2017_2025.loc[df_2017_2025["Unidade de Ensino"] == "Campus Porto Alegre Restinga"]
print("Após filtro Campus Restinga:", df_restinga.shape)

Após filtro Campus Restinga: (23819, 24)

#### 1.4 Exclusão de colunas desnecessárias ("Instituição", "Município", "UF", "Unidade de Ensino"):

In [72]:
df_restinga = df_restinga.drop(columns=["Instituição", "Município", "UF", "Unidade de Ensino"])
print("Após exclusão de colunas desnecessárias:", df_restinga.shape)

Após exclusão de colunas desnecessárias: (23819, 20)

#### 1.5 Verificação dos nomes dos cursos do Campus Restinga:

In [73]:
df_restinga.groupby("Nome de Curso").size()

Nome de Curso
Agente Cultural                                                        36
Agente de Desenvolvimento Cooperativista                               25
Agroecologia                                                           31
Análise e Desenvolvimento de Sistemas                                2515
Confeccionador de Bijuterias                                           25
Confeccionador de Bolsas em Tecido                                     25
Cuidador de Idoso                                                      25
Eletrônica Industrial                                                 982
Gestor de Microempresa                                                 59
Gestão Desportiva e de Lazer                                           84
Gestão desportiva e de Lazer                                          823
Letras                                                                177
Letras - Língua Estrangeira                                           805
Língua Brasileira de Sinais (Libras) ­ Básico                          25
Manufatura Avançada (industria 4.0)                                    47
Monitor de Atividades de Lazer                                         23
Operador de Computador                                                113
Processos Gerenciais                                                  934
Qualificação Profissional - Controle e Processos Industriais           36
Qualificação Profissional - Desenvolvimento Educacional e Social    10266
Qualificação Profissional - Gestão e Negócios                          41
Qualificação Profissional - Turismo, Hospitalidade e Lazer             41
Recepcionista em Serviços de Saúde                                     40
Técnico em Administração                                              168
Técnico em Agroecologia                                               903
Técnico em Comércio                                                   907
Técnico em Eletrônica                                                1266
Técnico em Guia de Turismo                                            614
Técnico em Informática                                               1331
Técnico em Informática Para Internet                                    3
Técnico em Informática para Internet                                  247
Técnico em Lazer                                                      881
Técnico em Recursos Humanos                                           197
Técnico em Redes de Computadores                                      124
dtype: int64

#### 1.6 Seleção dos cursos Técnicos e Superiores do Campus Restinga:

In [74]:
df_restinga["Tipo de Curso"].unique()

array(['Tecnologia', 'Técnico', 'Licenciatura',
       'Qualificação Profissional (FIC)', 'Especialização (Lato Sensu)'],
      dtype=object)

In [75]:
df_restinga = df_restinga[
    df_restinga["Tipo de Curso"].isin(["Licenciatura", "Técnico", "Tecnologia"])
]

In [76]:
# verificação dos nomes após seleção dos cursos técnicos e superiores:
df_contagem = df_restinga.groupby("Nome de Curso").size()
print(df_contagem)

Nome de Curso
Agroecologia                               31
Análise e Desenvolvimento de Sistemas    2515
Eletrônica Industrial                     982
Gestão Desportiva e de Lazer               84
Gestão desportiva e de Lazer              823
Letras                                    177
Letras - Língua Estrangeira               805
Processos Gerenciais                      934
Técnico em Administração                  168
Técnico em Agroecologia                   903
Técnico em Comércio                       907
Técnico em Eletrônica                    1266
Técnico em Guia de Turismo                614
Técnico em Informática                   1331
Técnico em Informática Para Internet        3
Técnico em Informática para Internet      247
Técnico em Lazer                          881
Técnico em Recursos Humanos               197
Técnico em Redes de Computadores          124
dtype: int64

#### 1.7 Limpeza dos cursos extintos e padronização dos nomes:

In [77]:
cursos_excluir = [
    "Técnico em Administração",
    "Técnico em Informática Para Internet",
    "Técnico em Informática para Internet",
    "Técnico em Recursos Humanos",
    "Técnico em Redes de Computadores",
    "Agroecologia"
]

df_restinga = df_restinga[
    ~df_restinga["Nome de Curso"].isin(cursos_excluir)
]

#exclusão do tecnico em informatica concomitante
df_restinga = df_restinga[
    ~(
        (df_restinga["Nome de Curso"] == "Técnico em Informática") &
        (df_restinga["Tipo de Oferta"] == "Concomitante")
    )
]

df_restinga.loc[:, "Nome de Curso"] = df_restinga["Nome de Curso"].replace({
    "Gestão desportiva e de Lazer": "Gestão Desportiva e de Lazer",
    "Letras": "Letras - Português e Espanhol",
    "Letras - Língua Estrangeira": "Letras - Português e Espanhol"
})

df_restinga["Nome de Curso"].unique()

array(['Análise e Desenvolvimento de Sistemas', 'Técnico em Eletrônica',
       'Gestão Desportiva e de Lazer', 'Eletrônica Industrial',
       'Técnico em Informática', 'Técnico em Guia de Turismo',
       'Técnico em Comércio', 'Técnico em Lazer',
       'Letras - Português e Espanhol', 'Processos Gerenciais',
       'Técnico em Agroecologia'], dtype=object)

#### 1.8 Verificando os valores ausentes:

In [78]:
df_restinga.isnull().sum()

Ano                                   0
Categoria da Situação                 0
Cor / Raça                            0
Código da Matricula                   0
Código do Ciclo Matricula             0
Data de Fim Previsto do Ciclo         0
Data de Inicio do Ciclo               0
Data de Ocorrencia da Matricula       0
Eixo Tecnológico                      0
Faixa Etária                          0
Mês De Ocorrência da Situação         2
Nome de Curso                         0
Renda Familiar                        0
Sexo                                  0
Situação de Matrícula                 0
Subeixo Tecnológico                   0
Tipo de Curso                         0
Tipo de Oferta                        0
Total de Inscritos                 1978
Turno                                 0
dtype: int64

#### 1.9 Tratamento dos valores ausentes:

In [79]:
#retirar coluna total inscritos, porque não será necessária ao cálculo dos indicadores
df_restinga = df_restinga.drop(columns=["Total de Inscritos"])
print("Após exclusão de total de inscritos:", df_restinga.shape)

Após exclusão de total de inscritos: (12024, 19)

In [80]:
#retirar as 2 linhas com valores nulos do mês de ocorrência

df_restinga.dropna(subset=["Mês De Ocorrência da Situação"], inplace=True) 

print("Após exclusão de linhas desnecessárias:", df_restinga.shape)

Após exclusão de linhas desnecessárias: (12022, 19)

In [81]:
df_restinga.isnull().sum()

Ano                                0
Categoria da Situação              0
Cor / Raça                         0
Código da Matricula                0
Código do Ciclo Matricula          0
Data de Fim Previsto do Ciclo      0
Data de Inicio do Ciclo            0
Data de Ocorrencia da Matricula    0
Eixo Tecnológico                   0
Faixa Etária                       0
Mês De Ocorrência da Situação      0
Nome de Curso                      0
Renda Familiar                     0
Sexo                               0
Situação de Matrícula              0
Subeixo Tecnológico                0
Tipo de Curso                      0
Tipo de Oferta                     0
Turno                              0
dtype: int64

#### 1.10 Verificando os tipos de dados:

In [82]:
df_restinga.dtypes

Ano                                 int64
Categoria da Situação              object
Cor / Raça                         object
Código da Matricula                 int64
Código do Ciclo Matricula           int64
Data de Fim Previsto do Ciclo      object
Data de Inicio do Ciclo            object
Data de Ocorrencia da Matricula    object
Eixo Tecnológico                   object
Faixa Etária                       object
Mês De Ocorrência da Situação      object
Nome de Curso                      object
Renda Familiar                     object
Sexo                               object
Situação de Matrícula              object
Subeixo Tecnológico                object
Tipo de Curso                      object
Tipo de Oferta                     object
Turno                              object
dtype: object

#### 1.11 Convertendo os tipos de dados:

In [83]:

df_restinga["Data de Fim Previsto do Ciclo"] = pd.to_datetime(
    df_restinga["Data de Fim Previsto do Ciclo"],
    dayfirst=True,
    errors='coerce'
)

df_restinga["Data de Inicio do Ciclo"] = pd.to_datetime(
    df_restinga["Data de Inicio do Ciclo"],
    dayfirst=True,
    errors='coerce'
)
df_restinga["Data de Ocorrencia da Matricula"] = pd.to_datetime(
    df_restinga["Data de Ocorrencia da Matricula"],
    dayfirst=True,
    errors='coerce'
)

df_restinga["Mês De Ocorrência da Situação"] = pd.to_datetime(
    df_restinga["Mês De Ocorrência da Situação"],
    dayfirst=True,
    errors='coerce'
)

df_restinga.dtypes

Ano                                         int64
Categoria da Situação                      object
Cor / Raça                                 object
Código da Matricula                         int64
Código do Ciclo Matricula                   int64
Data de Fim Previsto do Ciclo      datetime64[ns]
Data de Inicio do Ciclo            datetime64[ns]
Data de Ocorrencia da Matricula    datetime64[ns]
Eixo Tecnológico                           object
Faixa Etária                               object
Mês De Ocorrência da Situação      datetime64[ns]
Nome de Curso                              object
Renda Familiar                             object
Sexo                                       object
Situação de Matrícula                      object
Subeixo Tecnológico                        object
Tipo de Curso                              object
Tipo de Oferta                             object
Turno                                      object
dtype: object

#### 1.12 Ajustes das situações de matrícula:

In [84]:
df_restinga["Situação de Matrícula"].unique() # não há matrículas na situação Cancelada ou Reprovada (conforme PEPE)

array(['Em curso', 'Transf. externa', 'Desligada', 'Abandono',
       'Concluída', 'Integralizada', 'Transf. interna'], dtype=object)

In [85]:
# Ajuste das matrículas Em curso para Retido ou Em fluxo:
periodo_fim_previsto = df_restinga["Data de Fim Previsto do Ciclo"].dt.to_period("M")
periodo_referencia = pd.PeriodIndex.from_fields(
    year=df_restinga["Ano"], month=12, freq="M"
)

mask_em_curso = df_restinga["Situação de Matrícula"] == "Em curso"

mask_retido = (
    mask_em_curso
    & (periodo_fim_previsto < periodo_referencia)
)
df_restinga.loc[mask_em_curso, "Situação de Matrícula"] = "Em fluxo"
df_restinga.loc[mask_retido, "Situação de Matrícula"] = "Retido"

# Ajuste das matrículas Em fluxo para identificar os Ingressantes:
df_restinga.loc[(df_restinga["Situação de Matrícula"] == "Em fluxo") & (df_restinga["Data de Inicio do Ciclo"].dt.year == df_restinga["Ano"]), "Situação de Matrícula"] = "Ingressante"


# Ajuste das matrículas Concluída para Concluída no prazo ou Concluída com atraso:
periodo_conclusao = df_restinga["Mês De Ocorrência da Situação"].dt.to_period("M")

diferenca_meses = (df_restinga["Mês De Ocorrência da Situação"].dt.year - df_restinga["Data de Fim Previsto do Ciclo"].dt.year) * 12 + (df_restinga["Mês De Ocorrência da Situação"].dt.month - df_restinga["Data de Fim Previsto do Ciclo"].dt.month)

# Classificação: se o período de fim previsto é menor ou igual a 5 meses do mês de conclusão, considerei concluída no prazo

mask_concluida = df_restinga["Situação de Matrícula"] == "Concluída"

mask_no_prazo = (
    mask_concluida
    & (diferenca_meses <= 5)
)
df_restinga.loc[mask_concluida, "Situação de Matrícula"] = "Concluída com atraso"
df_restinga.loc[mask_no_prazo, "Situação de Matrícula"] = "Concluída no prazo"

df_restinga["Situação de Matrícula"].value_counts()

Situação de Matrícula
Em fluxo                4850
Ingressante             2741
Retido                  2710
Abandono                 588
Concluída no prazo       440
Concluída com atraso     301
Desligada                275
Transf. externa          106
Transf. interna            6
Integralizada              5
Name: count, dtype: int64

#### 1.13 Concatenação dos tipos de curso com o tipo de oferta e exclusão de coluna "Tipo de Oferta"

In [86]:
df_restinga["Tipo de Curso"].unique()

array(['Tecnologia', 'Técnico', 'Licenciatura'], dtype=object)

In [87]:
df_restinga["Tipo de Oferta"].unique()

array(['Não se aplica', 'Integrado', 'Subsequente', 'PROEJA - Integrado'],
      dtype=object)

In [88]:
# Licenciatura para Superior-Licenciatura
df_restinga.loc[
    df_restinga["Tipo de Curso"] == "Licenciatura",
    "Tipo de Curso"
] = "Superior-Licenciatura"

# Tecnologia para Superior-Tecnologia
df_restinga.loc[
    df_restinga["Tipo de Curso"] == "Tecnologia",
    "Tipo de Curso"
] = "Superior-Tecnologia"

# Técnico para Técnico + Tipo de Oferta
df_restinga.loc[df_restinga["Tipo de Curso"] == "Técnico", "Tipo de Curso"] = (
    "Técnico-" + df_restinga.loc[df_restinga["Tipo de Curso"] == "Técnico", "Tipo de Oferta"]
)

In [89]:
df_restinga["Tipo de Curso"].unique()

array(['Superior-Tecnologia', 'Técnico-Integrado', 'Técnico-Subsequente',
       'Técnico-PROEJA - Integrado', 'Superior-Licenciatura'],
      dtype=object)

In [90]:
df_restinga = df_restinga.drop(columns=["Tipo de Oferta"])
print("Após exclusão de colunas desnecessárias:", df_restinga.shape)

Após exclusão de colunas desnecessárias: (12022, 18)

#### 1.14 Padronização das Categorias de Situação de Matrícula:

In [91]:
df_restinga["Categoria da Situação"].unique()

array(['Em curso', 'Evadidos', 'Concluintes', 'Em Curso', 'Concluídos'],
      dtype=object)

In [92]:

concluidos = df_restinga[df_restinga["Categoria da Situação"].isin(["Concluídos"])]
concluidos["Situação de Matrícula"].unique()

array(['Concluída com atraso', 'Concluída no prazo'], dtype=object)

In [93]:
concluintes = df_restinga[df_restinga["Categoria da Situação"].isin(["Concluintes"])]
concluintes["Situação de Matrícula"].unique()

array(['Concluída no prazo', 'Integralizada', 'Concluída com atraso'],
      dtype=object)

In [94]:
# Padronização do nome da Categoria Situação Em Curso e Ajuste dos Concluídos para Concluintes (todos encontram-se em alguma Situação de Matrícula de finalização):
df_restinga.loc[:, "Categoria da Situação"] = df_restinga["Categoria da Situação"].replace({
    "Em Curso": "Em curso",
    "Concluídos": "Concluintes"
})

df_restinga["Categoria da Situação"].unique()

array(['Em curso', 'Evadidos', 'Concluintes'], dtype=object)

In [95]:
df_restinga["Categoria da Situação"].value_counts()

Categoria da Situação
Em curso       10301
Evadidos         975
Concluintes      746
Name: count, dtype: int64

#### 1.15 Verificação de duplicatas:

In [96]:
print("Quantidade de duplicatas: ",df_restinga.duplicated().sum())

Quantidade de duplicatas:  0

#### 1.16 Inspeção detalhada:

In [97]:
df_restinga.info(memory_usage='deep') #para verificar a utilização de memória real

<class 'pandas.core.frame.DataFrame'>
Index: 12022 entries, 20729 to 2365861
Data columns (total 18 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Ano                              12022 non-null  int64
 1   Categoria da Situação            12022 non-null  object
 2   Cor / Raça                       12022 non-null  object
 3   Código da Matricula              12022 non-null  int64
 4   Código do Ciclo Matricula        12022 non-null  int64
 5   Data de Fim Previsto do Ciclo    12022 non-null  datetime64[ns]
 6   Data de Inicio do Ciclo          12022 non-null  datetime64[ns]
 7   Data de Ocorrencia da Matricula  12022 non-null  datetime64[ns]
 8   Eixo Tecnológico                 12022 non-null  object
 9   Faixa Etária                     12022 non-null  object
 10  Mês De Ocorrência da Situação    12022 non-null  datetime64[ns]
 11  Nome de Curso                    12022 non-null  object
 12  Renda Familiar                   12022 non-null  object
 13  Sexo                             12022 non-null  object
 14  Situação de Matrícula            12022 non-null  object
 15  Subeixo Tecnológico              12022 non-null  object
 16  Tipo de Curso                    12022 non-null  object
 17  Turno                            12022 non-null  object
dtypes: datetime64[ns](4), int64(3), object(11)
memory usage: 9.8 MB

#### 1.17 Exportando o DataFrame para .parquet

In [98]:
df_restinga.to_parquet("../dados_tratados/restinga_dados_tratados.parquet", index=False)

In [99]:
#df_restinga.to_csv("restinga_dados_tratados.csv", index=False)