 ## 1 - Preparação dos Dados
Fonte: Microdados de Matrículas da Plataforma Nilo Peçanha (2017-2024)

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

#### 1.1 Transformação dos arquivos .csv em Data Frames, selecionando as colunas a serem utilizadas:

In [2]:
selecao = [
    "Ano", "Categoria da Situação", "Cor / Raça", "Código da Matricula", "Código do Ciclo Matricula", 
    "Data de Fim Previsto do Ciclo", "Data de Inicio do Ciclo", "Data de Ocorrencia da Matricula", 
    "Eixo Tecnológico", "Faixa Etária", "Instituição", "Município", "Mês De Ocorrência da Situação", 
    "Nome de Curso", "Renda Familiar", "Sexo", "Situação de Matrícula", "Subeixo Tecnológico", 
    "Tipo de Curso", "Tipo de Oferta", "Total de Inscritos", "Turno", "UF", "Unidade de Ensino"
]


df_2017 = pd.read_csv("../dados_brutos/microdados_matriculas_2017.csv", sep=";", usecols=selecao)
df_2018 = pd.read_csv("../dados_brutos/microdados_matriculas_2018.csv", sep=";", usecols=selecao)
df_2019 = pd.read_csv("../dados_brutos/microdados_matriculas_2019.csv", sep=";", usecols=selecao)
df_2020 = pd.read_csv("../dados_brutos/microdados_matriculas_2020.csv", sep=";", usecols=selecao)
df_2021 = pd.read_csv("../dados_brutos/microdados_matriculas_2021.csv", sep=";", usecols=selecao)
df_2022 = pd.read_csv("../dados_brutos/microdados_matriculas_2022.csv", sep=";", usecols=selecao)
df_2023 = pd.read_csv("../dados_brutos/microdados_matriculas_2023.csv", sep=";", usecols=selecao)
df_2024 = pd.read_csv("../dados_brutos/microdados_matriculas_2024.csv", sep=";", usecols=selecao)


print("Dimensão original 2017:", df_2017.shape)
print("Dimensão original 2018:", df_2018.shape)
print("Dimensão original 2019:", df_2019.shape)
print("Dimensão original 2020:", df_2020.shape)
print("Dimensão original 2021:", df_2021.shape)
print("Dimensão original 2022:", df_2022.shape)
print("Dimensão original 2023:", df_2023.shape)
print("Dimensão original 2024:", df_2024.shape)

Dimensão original 2017: (1031798, 24)
Dimensão original 2018: (964593, 24)
Dimensão original 2019: (1023303, 24)
Dimensão original 2020: (1507476, 24)
Dimensão original 2021: (1523346, 24)
Dimensão original 2022: (1513075, 24)
Dimensão original 2023: (1681363, 24)
Dimensão original 2024: (1982778, 24)

#### 1.2 Concatenação dos Data Frames gerados e exibição dos primeiros e últimos registros:

In [3]:
df_2017_2024 = pd.concat([df_2017, df_2018, df_2019, df_2020, df_2021, df_2022, df_2023, df_2024])

df_2017_2024.head()

,Ano,Categoria da Situação,Cor / Raça,Código da Matricula,Código do Ciclo Matricula,Data de Fim Previsto do Ciclo,Data de Inicio do Ciclo,Data de Ocorrencia da Matricula,Eixo Tecnológico,Faixa Etária,Instituição,Município,Mês De Ocorrência da Situação,Nome de Curso,Renda Familiar,Sexo,Situação de Matrícula,Subeixo Tecnológico,Tipo de Curso,Tipo de Oferta,Total de Inscritos,Turno,UF,Unidade de Ensino
0,2017,Em curso,Parda,72203790,2152673,31/12/2019,02/03/2017,01/03/2017,Produção Alimentícia,15 a 19 anos,IFRR,Norte,01/03/2017,Técnico em Agroindústria,"0,5<RFP<=1",M,Em curso,Agroindustria,Técnico,Integrado,52.0,Integral,RR,Campus Novo Paraíso
1,2017,Em curso,Parda,72203780,2152673,31/12/2019,02/03/2017,01/03/2017,Produção Alimentícia,15 a 19 anos,IFRR,Norte,01/03/2017,Técnico em Agroindústria,"1<RFP<=1,5",M,Em curso,Agroindustria,Técnico,Integrado,52.0,Integral,RR,Campus Novo Paraíso
2,2017,Evadidos,Preta,72203776,2152673,31/12/2019,02/03/2017,01/03/2017,Produção Alimentícia,15 a 19 anos,IFRR,Norte,01/07/2017,Técnico em Agroindústria,"0,5<RFP<=1",M,Transf. externa,Agroindustria,Técnico,Integrado,52.0,Integral,RR,Campus Novo Paraíso
3,2017,Em curso,Parda,72203774,2152673,31/12/2019,02/03/2017,01/03/2017,Produção Alimentícia,15 a 19 anos,IFRR,Norte,01/03/2017,Técnico em Agroindústria,"RFP>3,5",F,Em curso,Agroindustria,Técnico,Integrado,52.0,Integral,RR,Campus Novo Paraíso
4,2017,Em curso,Parda,72203772,2152673,31/12/2019,02/03/2017,01/03/2017,Produção Alimentícia,15 a 19 anos,IFRR,Norte,01/03/2017,Técnico em Agroindústria,"0,5<RFP<=1",M,Em curso,Agroindustria,Técnico,Integrado,52.0,Integral,RR,Campus Novo Paraíso

In [4]:
df_2017_2024.tail()

,Ano,Categoria da Situação,Cor / Raça,Código da Matricula,Código do Ciclo Matricula,Data de Fim Previsto do Ciclo,Data de Inicio do Ciclo,Data de Ocorrencia da Matricula,Eixo Tecnológico,Faixa Etária,Instituição,Município,Mês De Ocorrência da Situação,Nome de Curso,Renda Familiar,Sexo,Situação de Matrícula,Subeixo Tecnológico,Tipo de Curso,Tipo de Oferta,Total de Inscritos,Turno,UF,Unidade de Ensino
1982773,2024,Em curso,Parda,109548323,2965961,20/12/2025,27/02/2023,01/02/2023,Controle e Processos Industriais,15 a 19 anos,IF SUDESTE MG,Muriaé,25/02/2023,Técnico em Eletrotécnica,"0,5<RFP<=1",F,Em curso,Elétrica,Técnico,Integrado,96.0,Integral,MG,Campus Muriaé
1982774,2024,Concluintes,Parda,122954788,3139052,20/12/2024,01/07/2024,01/11/2024,Gestão e Negócios,35 a 39 anos,IFMS,Campo Grande,25/11/2024,Qualificação Profissional - Gestão e Negócios,"0,5<RFP<=1",M,Concluída,Gestão e Negócios,Qualificação Profissional (FIC),Concomitante,1346.0,NaN,MS,Campus Campo Grande
1982775,2024,Concluintes,Parda,99499494,2774414,01/03/2024,03/05/2021,01/05/2021,Gestão e Negócios,15 a 19 anos,IFPI,Oeiras,25/01/2024,Técnico em Administração,"0<RFP<=0,5",F,Concluída,Gestão e Negócios,Técnico,Integrado,154.0,Matutino,PI,Campus Oeiras
1982776,2024,Concluintes,Parda,106556867,2906230,31/01/2024,09/08/2022,01/08/2022,Gestão e Negócios,40 a 44 anos,IFPE,Cabo de Santo Agostinho,25/02/2024,Técnico em Logística,"0,5<RFP<=1",F,Concluída,Gestão e Negócios,Técnico,Subsequente,347.0,Vespertino,PE,Campus Cabo de Santo Agostinho
1982777,2024,Evadidos,Branca,111688442,2995963,31/07/2025,20/03/2023,01/03/2023,Informação e Comunicação,20 a 24 anos,IFCE,Canindé,25/12/2024,Técnico em Informática,Não declarada,F,Abandono,Informática,Técnico,Subsequente,35.0,Noturno,CE,Campus Canindé

#### 1.3 Aplicação de Filtro de Unidade de Ensino = Campus Porto Alegre Restinga:

In [5]:
df_restinga = df_2017_2024.loc[df_2017_2024["Unidade de Ensino"] == "Campus Porto Alegre Restinga"]
print("Após filtro Campus Restinga:", df_restinga.shape)

Após filtro Campus Restinga: (16850, 24)

#### 1.4 Exclusão de colunas desnecessárias ("Instituição", "Município", "UF", "Unidade de Ensino"):

In [6]:
df_restinga = df_restinga.drop(columns=["Instituição", "Município", "UF", "Unidade de Ensino"])
print("Após exclusão de colunas desnecessárias:", df_restinga.shape)

Após exclusão de colunas desnecessárias: (16850, 20)

#### 1.5 Verificação dos nomes dos cursos do Campus Restinga:

In [7]:
df_restinga.groupby("Nome de Curso").size()

Nome de Curso
Agente Cultural                                                       36
Agente de Desenvolvimento Cooperativista                              25
Análise e Desenvolvimento de Sistemas                               2209
Confeccionador de Bolsas em Tecido                                    25
Eletrônica Industrial                                                854
Gestor de Microempresa                                                29
Gestão Desportiva e de Lazer                                          84
Gestão desportiva e de Lazer                                         713
Letras                                                               177
Letras - Língua Estrangeira                                          620
Língua Brasileira de Sinais (Libras) ­ Básico                         25
Manufatura Avançada (industria 4.0)                                   15
Monitor de Atividades de Lazer                                        23
Operador de Computador                                                83
Processos Gerenciais                                                 764
Qualificação Profissional - Controle e Processos Industriais          36
Qualificação Profissional - Desenvolvimento Educacional e Social    5369
Técnico em Administração                                             168
Técnico em Agroecologia                                              747
Técnico em Comércio                                                  754
Técnico em Eletrônica                                               1076
Técnico em Guia de Turismo                                           554
Técnico em Informática                                              1126
Técnico em Informática Para Internet                                   3
Técnico em Informática para Internet                                 247
Técnico em Lazer                                                     769
Técnico em Recursos Humanos                                          195
Técnico em Redes de Computadores                                     124
dtype: int64

#### 1.6 Seleção dos cursos Técnicos e Superiores do Campus Restinga:

In [8]:
df_restinga["Tipo de Curso"].unique()

array(['Tecnologia', 'Técnico', 'Licenciatura',
       'Qualificação Profissional (FIC)', 'Especialização (Lato Sensu)'],
      dtype=object)

In [9]:
df_restinga = df_restinga[
    df_restinga["Tipo de Curso"].isin(["Licenciatura", "Técnico", "Tecnologia"])
]

In [10]:
# verificação dos nomes após seleção dos cursos técnicos e superiores:
df_contagem = df_restinga.groupby("Nome de Curso").size()
print(df_contagem)

Nome de Curso
Análise e Desenvolvimento de Sistemas    2209
Eletrônica Industrial                     854
Gestão Desportiva e de Lazer               84
Gestão desportiva e de Lazer              713
Letras                                    177
Letras - Língua Estrangeira               620
Processos Gerenciais                      764
Técnico em Administração                  168
Técnico em Agroecologia                   747
Técnico em Comércio                       754
Técnico em Eletrônica                    1076
Técnico em Guia de Turismo                554
Técnico em Informática                   1126
Técnico em Informática Para Internet        3
Técnico em Informática para Internet      247
Técnico em Lazer                          769
Técnico em Recursos Humanos               195
Técnico em Redes de Computadores          124
dtype: int64

#### 1.7 Limpeza dos cursos extintos e padronização dos nomes:

In [11]:
cursos_excluir = [
    "Técnico em Administração",
    "Técnico em Informática Para Internet",
    "Técnico em Informática para Internet",
    "Técnico em Recursos Humanos",
    "Técnico em Redes de Computadores"
]

df_restinga = df_restinga[
    ~df_restinga["Nome de Curso"].isin(cursos_excluir)
]

df_restinga.loc[:, "Nome de Curso"] = df_restinga["Nome de Curso"].replace({
    "Gestão desportiva e de Lazer": "Gestão Desportiva e de Lazer",
    "Letras": "Letras - Português e Espanhol",
    "Letras - Língua Estrangeira": "Letras - Português e Espanhol"
})

df_restinga["Nome de Curso"].unique()

array(['Análise e Desenvolvimento de Sistemas', 'Técnico em Eletrônica',
       'Gestão Desportiva e de Lazer', 'Eletrônica Industrial',
       'Técnico em Informática', 'Técnico em Guia de Turismo',
       'Técnico em Comércio', 'Técnico em Lazer',
       'Letras - Português e Espanhol', 'Processos Gerenciais',
       'Técnico em Agroecologia'], dtype=object)

#### 1.8 Verificando os valores ausentes:

In [12]:
df_restinga.isnull().sum()

Ano                                   0
Categoria da Situação                 0
Cor / Raça                            0
Código da Matricula                   0
Código do Ciclo Matricula             0
Data de Fim Previsto do Ciclo         0
Data de Inicio do Ciclo               0
Data de Ocorrencia da Matricula       0
Eixo Tecnológico                      0
Faixa Etária                          0
Mês De Ocorrência da Situação         2
Nome de Curso                         0
Renda Familiar                        0
Sexo                                  0
Situação de Matrícula                 0
Subeixo Tecnológico                   0
Tipo de Curso                         0
Tipo de Oferta                        0
Total de Inscritos                 1978
Turno                                 0
dtype: int64

#### 1.9 Tratamento dos valores ausentes:

In [13]:
#retirar coluna total inscritos, porque não será necessária ao cálculo dos indicadores
df_restinga = df_restinga.drop(columns=["Total de Inscritos"])
print("Após exclusão de total de inscritos:", df_restinga.shape)

Após exclusão de total de inscritos: (10447, 19)

In [14]:
#retirar as 2 linhas com valores nulos do mês de ocorrência

df_restinga.dropna(subset=["Mês De Ocorrência da Situação"], inplace=True) 

print("Após exclusão de linhas desnecessárias:", df_restinga.shape)

Após exclusão de linhas desnecessárias: (10445, 19)

In [15]:
df_restinga.isnull().sum()

Ano                                0
Categoria da Situação              0
Cor / Raça                         0
Código da Matricula                0
Código do Ciclo Matricula          0
Data de Fim Previsto do Ciclo      0
Data de Inicio do Ciclo            0
Data de Ocorrencia da Matricula    0
Eixo Tecnológico                   0
Faixa Etária                       0
Mês De Ocorrência da Situação      0
Nome de Curso                      0
Renda Familiar                     0
Sexo                               0
Situação de Matrícula              0
Subeixo Tecnológico                0
Tipo de Curso                      0
Tipo de Oferta                     0
Turno                              0
dtype: int64

#### 1.10 Verificando os tipos de dados:

In [16]:
df_restinga.dtypes

Ano                                 int64
Categoria da Situação              object
Cor / Raça                         object
Código da Matricula                 int64
Código do Ciclo Matricula           int64
Data de Fim Previsto do Ciclo      object
Data de Inicio do Ciclo            object
Data de Ocorrencia da Matricula    object
Eixo Tecnológico                   object
Faixa Etária                       object
Mês De Ocorrência da Situação      object
Nome de Curso                      object
Renda Familiar                     object
Sexo                               object
Situação de Matrícula              object
Subeixo Tecnológico                object
Tipo de Curso                      object
Tipo de Oferta                     object
Turno                              object
dtype: object

#### 1.11 Convertendo os tipos de dados:

In [17]:

df_restinga["Data de Fim Previsto do Ciclo"] = pd.to_datetime(
    df_restinga["Data de Fim Previsto do Ciclo"],
    dayfirst=True,
    errors='coerce'
)

df_restinga["Data de Inicio do Ciclo"] = pd.to_datetime(
    df_restinga["Data de Inicio do Ciclo"],
    dayfirst=True,
    errors='coerce'
)
df_restinga["Data de Ocorrencia da Matricula"] = pd.to_datetime(
    df_restinga["Data de Ocorrencia da Matricula"],
    dayfirst=True,
    errors='coerce'
)

df_restinga["Mês De Ocorrência da Situação"] = pd.to_datetime(
    df_restinga["Mês De Ocorrência da Situação"],
    dayfirst=True,
    errors='coerce'
)

df_restinga.dtypes

Ano                                         int64
Categoria da Situação                      object
Cor / Raça                                 object
Código da Matricula                         int64
Código do Ciclo Matricula                   int64
Data de Fim Previsto do Ciclo      datetime64[ns]
Data de Inicio do Ciclo            datetime64[ns]
Data de Ocorrencia da Matricula    datetime64[ns]
Eixo Tecnológico                           object
Faixa Etária                               object
Mês De Ocorrência da Situação      datetime64[ns]
Nome de Curso                              object
Renda Familiar                             object
Sexo                                       object
Situação de Matrícula                      object
Subeixo Tecnológico                        object
Tipo de Curso                              object
Tipo de Oferta                             object
Turno                                      object
dtype: object

#### 1.12 Ajustes das situações de matrícula:

In [18]:
df_restinga["Situação de Matrícula"].unique() # não há matrículas na situação Cancelada ou Reprovada (conforme PEPE)

array(['Em curso', 'Transf. externa', 'Desligada', 'Abandono',
       'Concluída', 'Integralizada', 'Transf. interna'], dtype=object)

In [19]:
# Ajuste das matrículas Em curso para Retido ou Em fluxo:
periodo_fim_previsto = df_restinga["Data de Fim Previsto do Ciclo"].dt.to_period("M")
periodo_referencia = pd.PeriodIndex.from_fields(
    year=df_restinga["Ano"], month=12, freq="M"
)

df_restinga.loc[df_restinga["Situação de Matrícula"] == "Em curso", "Situação de Matrícula"] = np.where(
    periodo_fim_previsto[df_restinga["Situação de Matrícula"] == "Em curso"] < periodo_referencia[df_restinga["Situação de Matrícula"] == "Em curso"],
    "Retido",
    "Em fluxo"
)

# Ajuste das matrículas Em fluxo para identificar os Ingressantes:
df_restinga.loc[(df_restinga["Situação de Matrícula"] == "Em fluxo") & (df_restinga["Data de Inicio do Ciclo"].dt.year == df_restinga["Ano"]), "Situação de Matrícula"] = "Ingressante"


# Ajuste das matrículas Concluída para Concluída no prazo ou Concluída com atraso:
periodo_conclusao = df_restinga["Mês De Ocorrência da Situação"].dt.to_period("M")

diferenca_meses = (df_restinga["Mês De Ocorrência da Situação"].dt.year - df_restinga["Data de Fim Previsto do Ciclo"].dt.year) * 12 + (df_restinga["Mês De Ocorrência da Situação"].dt.month - df_restinga["Data de Fim Previsto do Ciclo"].dt.month)

# Classificação: se o período de fim previsto é menor ou igual a 5 meses do mês de conclusão, considerei concluída no prazo
df_restinga.loc[df_restinga["Situação de Matrícula"] == "Concluída", "Situação de Matrícula"] = np.where(
    diferenca_meses[df_restinga["Situação de Matrícula"] == "Concluída"] <= 5,
    "Concluída no prazo",
    "Concluída com atraso"
)


df_restinga["Situação de Matrícula"].value_counts()

Situação de Matrícula
Em fluxo                4204
Ingressante             2480
Retido                  2316
Abandono                 449
Concluída no prazo       379
Concluída com atraso     259
Desligada                244
Transf. externa          103
Transf. interna            6
Integralizada              5
Name: count, dtype: int64

#### 1.13 Concatenação dos tipos de curso com o tipo de oferta e exclusão de coluna "Tipo de Oferta"

In [20]:
df_restinga["Tipo de Curso"].unique()

array(['Tecnologia', 'Técnico', 'Licenciatura'], dtype=object)

In [21]:
df_restinga["Tipo de Oferta"].unique()

array(['Não se aplica', 'Integrado', 'Subsequente', 'PROEJA - Integrado',
       'Concomitante'], dtype=object)

In [22]:
# Licenciatura para Superior-Licenciatura
df_restinga.loc[
    df_restinga["Tipo de Curso"] == "Licenciatura",
    "Tipo de Curso"
] = "Superior-Licenciatura"

# Tecnologia para Superior-Tecnologia
df_restinga.loc[
    df_restinga["Tipo de Curso"] == "Tecnologia",
    "Tipo de Curso"
] = "Superior-Tecnologia"

# Técnico para Técnico + Tipo de Oferta
df_restinga.loc[df_restinga["Tipo de Curso"] == "Técnico", "Tipo de Curso"] = (
    "Técnico-" + df_restinga.loc[df_restinga["Tipo de Curso"] == "Técnico", "Tipo de Oferta"]
)

In [23]:
df_restinga["Tipo de Curso"].unique()

array(['Superior-Tecnologia', 'Técnico-Integrado', 'Técnico-Subsequente',
       'Técnico-PROEJA - Integrado', 'Superior-Licenciatura',
       'Técnico-Concomitante'], dtype=object)

In [24]:
df_restinga = df_restinga.drop(columns=["Tipo de Oferta"])
print("Após exclusão de colunas desnecessárias:", df_restinga.shape)

Após exclusão de colunas desnecessárias: (10445, 18)

#### 1.14 Padronização das Categorias de Situação de Matrícula:

In [25]:
df_restinga["Categoria da Situação"].unique()

array(['Em curso', 'Evadidos', 'Concluintes', 'Em Curso', 'Concluídos'],
      dtype=object)

In [26]:

concluidos = df_restinga[df_restinga["Categoria da Situação"].isin(["Concluídos"])]
concluidos["Situação de Matrícula"].unique()

array(['Concluída com atraso', 'Concluída no prazo'], dtype=object)

In [27]:
concluintes = df_restinga[df_restinga["Categoria da Situação"].isin(["Concluintes"])]
concluintes["Situação de Matrícula"].unique()

array(['Concluída no prazo', 'Integralizada', 'Concluída com atraso'],
      dtype=object)

In [28]:
# Padronização do nome da Categoria Situação Em Curso e Ajuste dos Concluídos para Concluintes (todos encontram-se em alguma Situação de Matrícula de finalização):
df_restinga.loc[:, "Categoria da Situação"] = df_restinga["Categoria da Situação"].replace({
    "Em Curso": "Em curso",
    "Concluídos": "Concluintes"
})

df_restinga["Categoria da Situação"].unique()

array(['Em curso', 'Evadidos', 'Concluintes'], dtype=object)

In [29]:
df_restinga["Categoria da Situação"].value_counts()

Categoria da Situação
Em curso       9000
Evadidos        802
Concluintes     643
Name: count, dtype: int64

#### 1.15 Criação de coluna auxiliar ("Concluinte Previsto") para posterior cálculo do indicador de Taxa de Eficiência Acadêmica:

In [30]:
# marca True quando o ciclo deveria terminar no mesmo ano de referência da matrícula
df_restinga["Concluinte_Previsto"] = (
    df_restinga["Data de Fim Previsto do Ciclo"].dt.year == df_restinga["Ano"]
)
df_restinga.head()

,Ano,Categoria da Situação,Cor / Raça,Código da Matricula,Código do Ciclo Matricula,Data de Fim Previsto do Ciclo,Data de Inicio do Ciclo,Data de Ocorrencia da Matricula,Eixo Tecnológico,Faixa Etária,Mês De Ocorrência da Situação,Nome de Curso,Renda Familiar,Sexo,Situação de Matrícula,Subeixo Tecnológico,Tipo de Curso,Turno,Concluinte_Previsto
20729,2017,Em curso,Não declarada,44681986,1207788,2014-12-22,2012-03-05,2012-03-01,Informação e Comunicação,35 a 39 anos,2018-03-05,Análise e Desenvolvimento de Sistemas,Não declarada,F,Retido,Informática,Superior-Tecnologia,Matutino,False
42257,2017,Em curso,Branca,66262145,2007734,2019-12-20,2016-02-22,2016-02-01,Controle e Processos Industriais,15 a 19 anos,2016-02-01,Técnico em Eletrônica,"0,5<RFP<=1",F,Em fluxo,Elétrica,Técnico-Integrado,Matutino,False
42258,2017,Em curso,Branca,66262155,2007734,2019-12-20,2016-02-22,2016-02-01,Controle e Processos Industriais,15 a 19 anos,2016-02-01,Técnico em Eletrônica,"0,5<RFP<=1",F,Em fluxo,Elétrica,Técnico-Integrado,Matutino,False
42261,2017,Em curso,Branca,66262151,2007734,2019-12-20,2016-02-22,2016-02-01,Controle e Processos Industriais,15 a 19 anos,2016-02-01,Técnico em Eletrônica,"0<RFP<=0,5",F,Em fluxo,Elétrica,Técnico-Integrado,Matutino,False
42264,2017,Evadidos,Branca,66262139,2007734,2019-12-20,2016-02-22,2016-02-01,Controle e Processos Industriais,15 a 19 anos,2017-05-01,Técnico em Eletrônica,"0<RFP<=0,5",F,Transf. externa,Elétrica,Técnico-Integrado,Matutino,False

#### 1.16 Verificação de duplicatas:

In [31]:
print("Quantidade de duplicatas: ",df_restinga.duplicated().sum())

Quantidade de duplicatas:  0

#### 1.17 Inspeção detalhada:

In [32]:
df_restinga.info(memory_usage='deep') #para verificar a utilização de memória real

<class 'pandas.core.frame.DataFrame'>
Index: 10445 entries, 20729 to 1981342
Data columns (total 19 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Ano                              10445 non-null  int64
 1   Categoria da Situação            10445 non-null  object
 2   Cor / Raça                       10445 non-null  object
 3   Código da Matricula              10445 non-null  int64
 4   Código do Ciclo Matricula        10445 non-null  int64
 5   Data de Fim Previsto do Ciclo    10445 non-null  datetime64[ns]
 6   Data de Inicio do Ciclo          10445 non-null  datetime64[ns]
 7   Data de Ocorrencia da Matricula  10445 non-null  datetime64[ns]
 8   Eixo Tecnológico                 10445 non-null  object
 9   Faixa Etária                     10445 non-null  object
 10  Mês De Ocorrência da Situação    10445 non-null  datetime64[ns]
 11  Nome de Curso                    10445 non-null  object
 12  Renda Familiar                   10445 non-null  object
 13  Sexo                             10445 non-null  object
 14  Situação de Matrícula            10445 non-null  object
 15  Subeixo Tecnológico              10445 non-null  object
 16  Tipo de Curso                    10445 non-null  object
 17  Turno                            10445 non-null  object
 18  Concluinte_Previsto              10445 non-null  bool
dtypes: bool(1), datetime64[ns](4), int64(3), object(11)
memory usage: 8.5 MB

#### 1.18 Exportando o DataFrame para .parquet

In [33]:
df_restinga.to_parquet("restinga_dados_tratados.parquet", index=False)

In [34]:
#df_restinga.to_csv("restinga_dados_tratados.csv", index=False)